# .cargo/config.toml
#
# To find the library at run time

[install]
root = "../target"

[target.'cfg(all(target_os="macos"))']
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/../lib", 
    "-C", "link-arg=-Wl,-rpath,@executable_path/../lib/julia", 
]

[target.'cfg(all(target_os="linux"))']
rustflags = [
    "-C", "link-arg=-Wl,-rpath,$ORIGIN/../lib:$ORIGIN/../lib/julia",
]
